import type { Metadata } from 'next'
import './globals.css'
import { Provider } from '@/components/ui/provider'
import localFont from 'next/font/local'
import NavBar from '@/components/navbar/nav-bar'
import Noise from '@/components/noise/noise'

const ClashDisplay = localFont({
  src: '/fonts/ClashDisplay-Variable.ttf',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='es'>
      <body className={ClashDisplay.className}>
        <Noise />
        <Provider>
          <NavBar />
          {children}
        </Provider>
      </body>
    </html>
  )
}
