import type { Metadata } from 'next'
import './globals.css'
import { Provider } from '@/components/ui/provider'
import localFont from 'next/font/local'
import NavBar from '@/components/navbar/nav-bar'
import Noise from '@/components/noise/noise'
import { ReactLenis } from '@/utils/lenis'
import { ColorModeProvider } from '@/components/ui/color-mode'

const ClashDisplay = localFont({
  src: '/fonts/ClashDisplay-Variable.ttf',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='es'>
      <body className={ClashDisplay.className}>
        <ReactLenis root>
          <Noise />
          <Provider>
            <ColorModeProvider>
              <NavBar />
              {children}
            </ColorModeProvider>
          </Provider>
        </ReactLenis>
      </body>
    </html>
  )
}
